# Generated by Django 6.0.4 on 2026-04-30 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('student_number', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=20)),
                ('id_photo', models.ImageField(help_text='Upload a clear passport photo', upload_to='id_replace/photos/%Y/%m/%d/')),
                ('reason', models.TextField(blank=True, help_text='Why do you need a replacement ID? (Lost, Damaged, Stolen, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why the request was rejected (visible to student)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_replacements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_replacement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Replacement Request',
                'verbose_name_plural': 'ID Replacement Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
